spring.application.name=cee-wfe-userrole-client
service.protocol = https
application.name=@project.artifactId@
#server.port=80
server.port=9008
build.version=build_version

spring.profiles.active = local

# mongodb Configuration
#spring.data.mongodb.host=${MONGO_HOSTNAME}
#spring.data.mongodb.port=${MONGO_PORT}
#spring.data.mongodb.database=${MONGO_DBNAME}
#spring.data.mongodb.password=${MONGO_PASSWORD}
#spring.data.mongodb.username=${MONGO_USERNAME}

#spring.data.mongodb.uri=${MONGO_CONNECTION}


##logging
logging.level.org.springframework.data=debug
logging.level.=error

#EUREKA
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false






