server.port=<server_port>

# Mongo Database Setup
spring.data.mongodb.host=<ipaddress>
spring.data.mongodb.port=<port>
spring.data.mongodb.database=<cee_admin_portal>
spring.data.mongodb.password=<pwd>
spring.data.mongodb.username=<username>
