spring.profiles.active = local
service.protocol = https
spring.application.name=cee-wfe-userrole-client
application.name=@project.artifactId@
build.version=@project.version@

##logging
logging.level.org.springframework.data=debug
logging.level.=error

#EUREKA
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false