server.port=9007

## Mongo Database
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=cee_admin_portal

# spring.data.mongodb.host=54.87.90.72
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=
# spring.data.mongodb.password=ceeadmin123
# spring.data.mongodb.username=ceeadmin

##logging
logging.level.org.springframework.data=debug
logging.level.=error
